// This file is automatically generated. Do not modify it manually.
// Code generated .* DO NOT EDIT.

package main

import (
	root "github.com/mattermost/mattermost-plugin-nps/server"
)

// the manifest is automatically generated from plugin.json at the root of the project
var manifest = root.Manifest
